# Generated by Django 6.1 on 2026-10-05 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('spareparts', '0002_rename_spareparts_sparepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_parts', to='service.service')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_usages', to='spareparts.sparepart')),
            ],
            options={
                'unique_together': {('service', 'spare_part')},
            },
        ),
    ]
