# Generated by Django 6.1 on 2026-10-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicesparepart_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesparepart',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
