# Generated by Django 6.1 on 2026-10-06 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('spareparts', '0002_rename_spareparts_sparepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSpareParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='service.service')),
                ('spare_part_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_spare_parts', to='spareparts.sparepart')),
            ],
        ),
    ]
