# Generated by Django 6.1 on 2026-10-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_spare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicespareparts',
            old_name='spare_part_name',
            new_name='spare_part',
        ),
    ]
