# Generated by Django 6.1 on 2026-09-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpareParts',
            new_name='SparePart',
        ),
    ]
