# Generated by Django 6.1 on 2026-08-25 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_alter_customer_address_alter_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=45)),
                ('year', models.PositiveIntegerField()),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('VAN', 'Van'), ('MOTORCYCLE', 'Motorcycle'), ('THREEWHEELER', 'Three Wheeler'), ('SUV', 'SUV'), ('OTHERS', 'Others')], default='MOTORCYCLE', max_length=15)),
                ('current_mileage', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='customer.customer')),
            ],
        ),
    ]
