# Generated by Django 6.1 on 2026-08-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'Car'), ('VAN', 'Van'), ('MOTORCYCLE', 'Motorcycle'), ('THREEWHEELER', 'Three Wheeler'), ('SUV', 'SUV'), ('OTHERS', 'Others')], db_index=True, default='MOTORCYCLE', max_length=15),
        ),
    ]
