# Generated by Django 6.1 on 2026-08-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_options_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='other_vehicle_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
